import {
  cardImage1,
  cardImage2,
  cardImage3,
  cardImage4,
  cardImage5,
  cardImage6,
  cardImage7,
  thumbnail1,
  thumbnail2,
  thumbnail3,
  thumbnail4,
  thumbnail5,
  soundWhiteNoise,
  soundNight,
  soundPiano,
  soundLounge,
  soundWolf,
  soundRiver,
  soundOcean,
  soundThunder,
  soundCoffee,
  soundTabla,
  soundWaves,
  soundBirds,
  soundWaterfall,
  soundAstral,
  soundGong,
  soundWinds,
  soundFireplace,
  soundZen,
  avatar,
} from "../Assets/images";

export const currentUser = {
  name: "Trouble Maker",
  email: "email@email.com",
  image: avatar,
};

export const sounds = [
  {
    id: 1,
    title: "White Noise",
    image: cardImage1,
    thumbnail: soundWhiteNoise,
    premium: false,
  },
  {
    id: 2,
    title: "Night",
    image: cardImage6,
    thumbnail: soundNight,
    premium: false,
  },
  {
    id: 3,
    title: "Piano",
    image: cardImage3,
    thumbnail: soundPiano,
    premium: false,
  },
  {
    id: 4,
    title: "Lounge",
    image: cardImage4,
    thumbnail: soundLounge,
    premium: false,
  },
  {
    id: 5,
    title: "Wolf",
    image: cardImage5,
    thumbnail: soundWolf,
    premium: true,
  },
  {
    id: 6,
    title: "River",
    image: cardImage6,
    thumbnail: soundRiver,
    premium: true,
  },
  {
    id: 7,
    title: "Ocean",
    image: cardImage7,
    thumbnail: soundOcean,
    premium: true,
  },
  {
    id: 8,
    title: "Thunder",
    image: cardImage4,
    thumbnail: soundThunder,
    premium: false,
  },
  {
    id: 9,
    title: "Coffee Shop",
    image: cardImage1,
    thumbnail: soundCoffee,
    premium: true,
  },
  {
    id: 10,
    title: "Tabla",
    image: cardImage4,
    thumbnail: soundTabla,
    premium: true,
  },
  {
    id: 11,
    title: "Waves",
    image: cardImage7,
    thumbnail: soundWaves,
    premium: true,
  },
  {
    id: 12,
    title: "Birds",
    image: cardImage2,
    thumbnail: soundBirds,
    premium: false,
  },
  {
    id: 13,
    title: "Waterfall",
    image: cardImage3,
    thumbnail: soundWaterfall,
    premium: false,
  },
  {
    id: 14,
    title: "Astral",
    image: cardImage6,
    thumbnail: soundAstral,
    premium: true,
  },
  {
    id: 15,
    title: "Gong",
    image: cardImage4,
    thumbnail: soundGong,
    premium: true,
  },
  {
    id: 16,
    title: "Winds",
    image: cardImage5,
    thumbnail: soundWinds,
    premium: true,
  },
  {
    id: 17,
    title: "Fireplace",
    image: cardImage1,
    thumbnail: soundFireplace,
    premium: false,
  },
  {
    id: 18,
    title: "Zen",
    image: cardImage3,
    thumbnail: soundZen,
    premium: true,
  },
];

export const meditation = [
  {
    id: 1,
    title: "Meditation Exercise 1",
    image: cardImage5,
    thumbnail: thumbnail1,
    duration: "05:22",
    genre: "Children",
  },
  {
    id: 2,
    title: "Meditation Exercise 2",
    image: cardImage7,
    thumbnail: thumbnail2,
    duration: "02:05",
    genre: "Mature",
  },
  {
    id: 3,
    title: "Meditation Exercise 3",
    image: cardImage4,
    thumbnail: thumbnail3,
    duration: "03:19",
    genre: "Adventure",
  },
  {
    id: 4,
    title: "Meditation Exercise 4",
    image: cardImage1,
    thumbnail: thumbnail4,
    duration: "03:11",
    genre: "Fable",
  },
  {
    id: 5,
    title: "Meditation Exercise 5",
    image: cardImage3,
    thumbnail: thumbnail5,
    duration: "08:44",
    genre: "Children",
  },
  {
    id: 6,
    title: "Meditation Exercise 6",
    image: cardImage7,
    thumbnail: thumbnail2,
    duration: "12:16",
    genre: "Fairytale",
  },
  {
    id: 7,
    title: "Meditation Exercise 7",
    image: cardImage2,
    thumbnail: thumbnail4,
    duration: "04:52",
    genre: "Fantasy",
  },
  {
    id: 8,
    title: "Meditation Exercise 8",
    image: cardImage3,
    thumbnail: thumbnail1,
    duration: "07:56",
    genre: "Happy",
  },
];

export const stories = [
  {
    id: 1,
    title: "The Boy Who Cried Wolf",
    image: cardImage2,
    thumbnail: thumbnail1,
    duration: "05:22",
    genre: "Children",
  },
  {
    id: 2,
    title: "Old Man and the Sea",
    image: cardImage6,
    thumbnail: thumbnail2,
    duration: "02:05",
    genre: "Mature",
  },
  {
    id: 3,
    title: "Jack and the Beanstalk",
    image: cardImage1,
    thumbnail: thumbnail1,
    duration: "03:19",
    genre: "Adventure",
  },
  {
    id: 4,
    title: "The Tale of Peter Rabbit",
    image: cardImage5,
    thumbnail: thumbnail4,
    duration: "03:11",
    genre: "Fable",
  },
  {
    id: 5,
    title: "The Tortoise and the Hare",
    image: cardImage7,
    thumbnail: thumbnail5,
    duration: "08:44",
    genre: "Children",
  },
  {
    id: 6,
    title: "The Farmer and the Well",
    image: cardImage2,
    thumbnail: thumbnail2,
    duration: "12:16",
    genre: "Fairytale",
  },
  {
    id: 7,
    title: "Lttle Red Riding Hood",
    image: cardImage4,
    thumbnail: thumbnail4,
    duration: "04:52",
    genre: "Fantasy",
  },
  {
    id: 8,
    title: "The Wizard of Oz",
    image: cardImage6,
    thumbnail: thumbnail1,
    duration: "07:56",
    genre: "Happy",
  },
];

export const articles = [
  {
    id: 1,
    title: "Restless Leg Syndrome",
    image: cardImage6,
    thumbnail: thumbnail1,
    duration: "05:22",
    genre: "Circadian Rhythm Disorders",
  },
  {
    id: 2,
    title: "Sleepwalking",
    image: cardImage1,
    thumbnail: thumbnail2,
    duration: "05:22",
    genre: "Pediatrics",
  },
  {
    id: 3,
    title: "Night Terrors",
    image: cardImage3,
    thumbnail: thumbnail3,
    duration: "05:22",
    genre: "Sleep and Wellness",
  },
  {
    id: 4,
    title: "Narcolepsy",
    image: cardImage4,
    thumbnail: thumbnail1,
    duration: "05:22",
    genre: "Parasomnias",
  },
  {
    id: 5,
    title: "Sleep and Exercise",
    image: cardImage2,
    thumbnail: thumbnail5,
    duration: "05:22",
    genre: "Hypersomnia",
  },
  {
    id: 6,
    title: "Treating OSA with Diet and Exercise without Weight Loss",
    image: cardImage7,
    thumbnail: thumbnail3,
    duration: "05:22",
    genre: "Insomnia",
  },
  {
    id: 7,
    title: "Bad Dreams and the Risk of Dimentia",
    image: cardImage2,
    thumbnail: thumbnail1,
    duration: "05:22",
    genre: "Sleep Hygine",
  },
];
